name = "redirect-analyzer-api"
main = "worker.js"
compatibility_date = "2024-10-01"

# KV namespaces for data storage (replaces SQLite)
[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "REPLACE_WITH_YOUR_KV_ID"

[[kv_namespaces]]
binding = "ANALYTICS_DATA" 
id = "REPLACE_WITH_YOUR_KV_ID"

[[kv_namespaces]]
binding = "API_KEYS"
id = "REPLACE_WITH_YOUR_KV_ID"

# Environment variables
[vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
MAX_REDIRECTS = "15"
REQUEST_TIMEOUT = "8000"

# Worker limits and configuration
[limits]
cpu_ms = 30000

# Development environment
[env.development]
name = "redirect-analyzer-api-dev"

[env.development.vars]
ENVIRONMENT = "development"
API_VERSION = "1.0.0-dev"
